name = "https://cloudflare-google-chat-ai.chtr-418.workers.dev/"
main = "index.js"
compatibility_date = "2024-04-03"

# Variables d'environnement publiques
[vars]
EMAIL_ID = "AI-Zero-Trust@serverweb3.xyz"
JWKS_URL = "https://rowbinweb-sec.cloudflareaccess.com/cdn-cgi/access/certs"

# Liaisons de ressources
[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "network_logs"
database_id = "ae0e26c7-f960-4d0b-bcc4-9e7d5c4a7580"
